version: 0.0
os: linux
files:
 - source: /home/ec2-user/Wenzer_Project/wenzer_web/build
   destination: /var/www/html
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root